# Generated by Django 4.0.1 on 2022-01-22 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson14', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passport',
            name='exp_date',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='passport',
            name='pass_number',
            field=models.CharField(max_length=20),
        ),
    ]
